spring:
  application:
    name: springcache
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false # Recommended for production to avoid N+1 issues
    hibernate:
      ddl-auto: create-drop # Use 'update' or 'validate' in production
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true # Makes SQL easier to read in colorful themes
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

logging:
  level:
    root: INFO
    # Target your specific package for your Mapper and Exception Handler
    com.testingapp.testingapp: DEBUG
    com.testingapp.testingapp.mapper: TRACE
    com.testingapp.testingapp.advice: TRACE
  file:
    name: logs/springcache.log
  logback:
    rollingpolicy:
      # These must be on the same line as the key
      max-file-size: 100MB
      max-history: 7
